name:                timer
version:             0.1.0.0
github:              "emilyhorsman/timer"
license:             BSD3
author:              "Emily Horsman"
maintainer:          "me@emilyhorsman.com"
copyright:           "2018 Emily Horsman"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/timer#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2 && < 1
- cassava >= 0.5.1.0 && < 1
- directory >= 1.1.0.0 && < 2
- time >= 1.8.0.2 && < 2
- unix >= 2.7.2.2 && < 3
- vector >= 0.12.0.1 && < 1

library:
  source-dirs: src

executables:
  timer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timer

tests:
  timer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timer
